export const ICONS = {
  /* Icon */
  bell: "/icon/bell.svg",
  bellActive: "/icon/bell-active.svg",
  bellWhite: "/icon/bell-white.svg",
  bellWhiteActive: "/icon/bell-white-active.svg",
  search: "/icon/search.svg",
  searchWhite: "/icon/search-white.svg",
  ranking1: "/icon/ranking1.svg",
  ranking2: "/icon/ranking2.svg",
  ranking3: "/icon/ranking3.svg",
  boardLike: "/icon/board-like.svg",
  boardComment: "/icon/board-comment.svg",
  cardLike: "/icon/card-like.svg",
  cardComment: "/icon/card-comment.svg",
  cardSaveOff: "/icon/card-save-off.svg",
  cardSaveOn: "/icon/card-save-on.svg",
  cardLikeOff: "/icon/card-like-off.svg",
  cardLikeOn: "/icon/card-like-on.svg",
  cardDot: "/icon/card-dot.svg",
  cardArrowRight: "/icon/card-arrow-right.svg",
  cardArrowLeft: "/icon/card-arrow-left.svg",
  up: "/icon/up.svg",
  x: "/icon/x.svg",
  checkbox: "/icon/checkbox.svg",
  checkedbox: "/icon/checkedbox.svg",
  kakao: "/icon/kakao.svg",
  google: "/icon/google.svg",
  success: "/icon/toast-success.svg",
  error: "/icon/toast-error.svg",
  warning: "/icon/toast-warning.svg",
  information: "/icon/toast-information.svg",
  link: "/icon/link.svg",
  overlap: "/icon/overlap.svg",
};
